### ISSUE TITLE
Can't install Torus FlexVolume plugin in CoreOS.

### ISSUE THREAD

**Issue by gosharplite** [coreos/torus#265]
In CoreOS, /usr is a 'Read-only file system'. Below commands do not work.

```
mkdir -p /usr/libexec/kubernetes/kubelet-plugins/volume/exec/coreos.com~torus/
cp torusblk /usr/libexec/kubernetes/kubelet-plugins/volume/exec/coreos.com~torus/torus
```

Is there another way to install FlexVolume plugin in CoreOS?

**Comment by gosharplite** [comment]
In your AWS script, kubelet needs below parameter.
```
--volume-plugin-dir=/etc/kubernetes/volumeplugins
```
I will give it a try.

**Comment by gosharplite** [comment]
Version of my k8s cluster is shown below.
```
$ ./kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"5cb86ee022267586db386f62781338b0483733b3", GitTreeState:"clean"}
```
I can follow your example [Run Torus on Kubernetes](https://github.com/coreos/torus/tree/master/contrib/kubernetes) up to step 5, Create a volume.
```
$ ./torusctl -C 10.128.112.22:32379 list-peers
+-------------------------+--------------------------------------+---------+------+--------+---------------+--------------+
|         ADDRESS         |                 UUID                 |  SIZE   | USED | MEMBER |    UPDATED    | REB/REP DATA |
+-------------------------+--------------------------------------+---------+------+--------+---------------+--------------+
| http://10.2.0.64:40000  | 0d6d13a6-3207-11e6-9050-4e73b393e21b | 2.0 GiB | 0 B  | OK     | 4 seconds ago | 0 B/sec      |
| http://10.2.0.6:40000   | fab56883-3206-11e6-8955-76fa7f449663 | 2.0 GiB | 0 B  | OK     | now           | 0 B/sec      |
| http://10.2.0.128:40000 | fb1ff354-3206-11e6-8e18-8e70be9624db | 2.0 GiB | 0 B  | OK     | 3 seconds ago | 0 B/sec      |
+-------------------------+--------------------------------------+---------+------+--------+---------------+--------------+
Balanced: true Usage:  0.00%

$ ./torusblk -C 10.128.112.22:32379 volume create pg1 2GiB
```
However `postgres-oneshot.yaml` does not work. There is no devices available.
```
$ ./kubectl describe po postgres-torus-92650690-9cow4
Name:		postgres-torus-92650690-9cow4
Namespace:	tyd
Node:		10.128.112.24/10.128.112.24
Start Time:	Tue, 14 Jun 2016 16:27:09 +0800
Labels:		app=postgres-torus,pod-template-hash=92650690
Status:		Pending
IP:		
Controllers:	ReplicaSet/postgres-torus-92650690
Containers:
  postgres:
    Container ID:	
    Image:		postgres
    Image ID:		
    Port:		5432/TCP
    QoS Tier:
      memory:		BestEffort
      cpu:		BestEffort
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment Variables:
      POD_IP:			 (v1:status.podIP)
      POSTGRES_PASSWORD:	testtorus
      PGDATA:			/var/lib/postgresql/data/pgdata
Conditions:
  Type		Status
  Ready 	False 
Volumes:
  data:
  <unknown>
  default-token-iyxs6:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-iyxs6
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  27m		27m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned postgres-torus-92650690-9cow4 to 10.128.112.24
  27m		5s		125	{kubelet 10.128.112.24}			Warning		FailedMount	Unable to mount volumes for pod "postgres-torus-92650690-9cow4_tyd(c9192682-3209-11e6-a0b0-5254005f9388)": attach command failed, status: Failure, reason: no devices available
  27m		5s		125	{kubelet 10.128.112.24}			Warning		FailedSync	Error syncing pod, skipping: attach command failed, status: Failure, reason: no devices available
```
Wish I know how to debug this situation further.

**Comment by gosharplite** [comment]
Here are the yaml files.

torus-k8s-oneshot.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: etcd-torus
  name: etcd-torus
spec:
  type: NodePort
  ports:
    - port: 2379
      name: etcd-client
      targetPort: etcd-client
      nodePort: 32379
  selector:
    name: etcd-torus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: etcd-torus-internal
  name: etcd-torus-internal
spec:
  clusterIP: 10.1.0.100
  ports:
    - port: 2379
      name: etcd-client
      targetPort: etcd-client
  selector:
    name: etcd-torus
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    name: etcd-torus
  name: etcd-torus
spec:
  containers:
  - image: quay.io/coreos/etcd:v3.0.0-beta.0
    name: etcd-torus
    ports:
    - name: etcd-peers
      containerPort: 2380
    - name: etcd-client
      containerPort: 2379
    volumeMounts:
    - name: data
      mountPath: /var/lib/etcd
    env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: ETCD_DATA_DIR
      value: /var/lib/etcd
    - name: ETCD_NAME
      value: etcd
    - name: ETCD_INITIAL_CLUSTER
      value: etcd=http://$(POD_IP):2380
    - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
      value: http://$(POD_IP):2380
    - name: ETCD_ADVERTISE_CLIENT_URLS
      value: http://$(POD_IP):2379
    - name: ETCD_LISTEN_CLIENT_URLS
      value: http://0.0.0.0:2379
    - name: ETCD_LISTEN_PEER_URLS
      value: http://$(POD_IP):2380
  volumes:
    - name: data
      emptyDir: {}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: torus
  labels:
    app: torus
spec:
  template:
    metadata:
      name: torus
      labels:
        daemon: torus
    spec:
      containers:
      - name: torus
        image: quay.io/coreos/torus:latest
        ports:
        - name: peer
          containerPort: 40000
        - name: http
          containerPort: 4321
        env:
        - name: ETCD_HOST
          value: $(ETCD_TORUS_SERVICE_HOST)
        - name: STORAGE_SIZE
          value: 2GiB
        - name: LISTEN_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: AUTO_JOIN
          value: "1"
        - name: DEBUG_INIT
          value: "1"
        - name: DROP_MOUNT_BIN
          value: "0"
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
        - name: data
          hostPath:
            path: /srv/torus
      imagePullSecrets:
        - name: quay-torus
```
postgres-oneshot.yaml
```
apiVersion: v1
kind: Service
metadata:
  labels:
    name: postgres-torus
  name: postgres-torus
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: postgres-client
      nodePort: 30432
  selector:
    app: postgres-torus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-torus
  labels:
    app: postgres-torus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-torus
    spec:
      containers:
      - image: postgres
        name: postgres
        ports:
        - name: postgres-client
          containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POSTGRES_PASSWORD
          value: testtorus
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
      volumes:
        - name: data
          flexVolume:
            driver: "coreos.com/torus"
            fsType: "ext4"
            options:
              volume: "pg1"
              etcd: "10.1.0.100:2379"
```
